### PR TITLE
Pull request-7/15/2020

### PR DESCRIPTION
**Pull request by c0mmander8**

### CODE REVIEW

**Comment by MarcoVerpelli** [comment]
Just a little note:
as already pointed out to the AppleWin folks
Solid Apple is used in the technical manual for //c
Closed Apple practically everywhere else.

So it's probably just a matter of when one approached the Apple II world
<1984 nothing at all or Closed
>1984 Solid

Marco

**Comment by inexorabletash** [comment]
Thanks!

**Comment by inexorabletash** [comment]
Re: "Solid" vs. "Closed". I'm sure Apple started off with "Closed" for some reason (Open and Closed are clearer antonyms) but "Closed" has negative connotations and doesn't describe the glyph.

Mentally, I'm looking at the documentation as being a late-1980s iteration of Apple's docs, so trying to adhere to later rather than earlier conventions, even though most users may be familiar with earlier ones.

**Comment by inexorabletash** [comment]
That said, I type "Closed-Apple" reflexively, so fixes to make that say "Solid" are appreciated!

Also, more generally, I can imagine wanting to distinguish behavior with Open vs. Solid Apple to allow more control/commands. Until then, though, unifying the documentation is probably a good idea.

**Pull request merged**
