### PR TITLE
Pull request-9/28/2020

### PR DESCRIPTION
**Pull request by c0mmander8**

### CODE REVIEW

**Comment by c0mmander8** [comment]
This pull request replaces the pull request from 9/17/2020. Please close that pull request without merging it.

**Comment by c0mmander8** [comment]
In light of commit 001b124, this pull request replaces the pull request from 9/17/2020. Please close that pull request without merging it.

**Comment by c0mmander8** [comment]
In light of commit 001b124, this pull request replaces the pull request from 9/17/2020. Close that pull request without merging it.

**Comment by c0mmander8** [comment]
In light of commit 001b124, this pull request replaces the pull request from 9/17/2020. Close that pull request without merging it.

**Comment by inexorabletash** [comment]
Not substantive.

**Comment by c0mmander8** [comment]
Reopen and merge this pull request, because I need this pull request merged before I can delete my existing fork of this repository and clone a new fork of this repository with all the changes you have made since my existing fork was branched off.

**Comment by c0mmander8** [comment]
As referenced in pull request #290, reopen and merge this pull request, because I need this pull request merged before I can delete my existing fork of this repository and clone a new fork of this repository with all the changes you have made since my existing fork was branched off.

**Comment by inexorabletash** [comment]
That is not a compelling argument to merge a PR. You should be able to delete regardless. Git is a distributed version control system and no activity in another fork should impede work done elsewhere.

**Pull request closed without merging**
