### PR TITLE
More fonts

### PR DESCRIPTION
**Pull request by RebeccaRGB**
These are MGTK conversions of some of my bitmap fonts, Fairfax, Magdalena, McMillen, Mischke, and Monterey. I converted these as part of adding support for the MGTK font format to my bitmap font editor, Kreative Bits'n'Picas. You can have them if you want them. :)

### CODE REVIEW

**Comment by inexorabletash** [comment]
Very cool! When I looked at the Fairfax font, some of the symbol characters (©️®️) seem to be missing the left hand edge, and the folder/file/glyphs seem truncated. I'll post an image when I can, but can you verify your conversion logic?

**Comment by inexorabletash** [comment]
I guess it just affects the Fairfax variations. Look at the ©️ and ®️ glyphs:

image
image
image
image

Also, changing the sizes of the symbol glyphs (specifically, the folder/file/drive, maybe the arrows) is probably not a good idea as some layout depends on them. That said, fonts other than System and Monaco are really not useful for anything and changing the system font in A2D can only be done with a recompile, so it's not a big deal.

**Comment by RebeccaRGB** [comment]
The ® and © glyphs are supposed to be missing the left edge; it's in the original:

Screenshot from 2023-11-07 11-14-57

It's a design choice that dates back to the original Monaco on the Macintosh:

Screenshot from 2023-11-07 11-20-24

.epo is Esperanto and .qmk is Mikiana, another constructed language. Without a translation I guess they don't really serve a purpose, so they can be removed.

**Comment by inexorabletash** [comment]
Thanks for clarifying! A few notes for posterity:

* The glyphs in code points 0...31 only really matter in the System font (and any hypothetical future ability to swap the system font in A2D). So maintaining those isn't really critical.
* Even then, the only glyphs that are actually used are: 0x00 (spacer), 0x01...0x06 (left/right halves of folder/file/disk), 0x08/0x15/0x0B/0x0A (left/right/up/down arrows), 0x0D (carriage return), 0x16 (degree sign), 0x1E/0x1F (solid/open apple), and 0x1D (checkmark). Documented in the common.inc file.
* You've probably noticed but the text encodings are based on Apple's Apple II character ROM variations (and the Brazilian TK3000 clone). The intent here is that if e.g. a French user had text files from the 1980s they would appear correctly.  These swap out a few places in ASCII. For Spanish and Dutch I used a few code units 0x10...0x14 to get a few more characters. The full mapping to/from Unicode is defined in bin/transcode.pl which is used to generate the localized resources. 
* If I need to steal more C0 code points in the future for symbols, System.en and the new fonts will get out of sync. It won't hurt anything, though.

**Comment by inexorabletash** [comment]
Thank you!

**Pull request merged**
